### ISSUE TITLE
Customising method

### ISSUE THREAD

**Issue by michaeldaltonau** [Homemadestea58/Links-Portal#21]
How should we customise hiding/showing tiles on the links portal?
The options are to have controls on the portal, or to link to a customise page.
The latter will require less coding and would be a bit simpler to maintain.
Please comment with your thoughts and I shall try to start on it soon

**Comment by michaeldaltonau** [comment]
Att hem ome ntI hav ebe gun dev elo pin gan sep era tep age.

**Comment by homemadestea58** [comment]
What does that mean

**Comment by michaeldaltonau** [comment]
## That was an extremely fast reply!!
Sorry, the spacing didn't work right. It should have said

> At the moment I have begun developing a seperate page.

**Comment by homemadestea58** [comment]
Is it  up on your repo

**Comment by michaeldaltonau** [comment]
> Is it up on your repo

Yes, it is down the bottom.
It is just design at the moment, I haven't coded it yet.

**Comment by michaeldaltonau** [comment]
Do you like the design?

**Comment by homemadestea58** [comment]
Ok
