### ISSUE TITLE
New JSON is not working

### ISSUE THREAD

**Issue by homemadestea58** [Homemadestea58/Links-Portal#35]
JSON not working

**Comment by michaeldaltonau** [comment]
@Homemadestea58 
## Please answer <ins>**_all_**</ins> the following questions, because there is no way to reproduce this bug currently
1. Was this on the filtered network (you know what I mean) or the other network?
2. What browser did you use to do this (Please mention browser, device, device version, and browser version)
3. If on iOS/iPadOS was a VPN used?
4. Did you access it via GitHub pages? If true, who's fork did you use?
5. Did you access it via links-p.cf?
6. Did you access it via a local copy (Apache)?
7. Was JavaScript enabled on the browser?

### Then comment back with the results

### After that, reproduce the results on a desktop browser with a dev console, and make another comment with the results of the JS console.

**Comment by SuperMario22922** [comment]
# llui85 question answers
1. it was on the filtered network and it worked on links-p.cf but not on github pages
2. ios 12.4.1, chrome browser, ipad 5th generation
3. no
4. accessed through github pages and did not work
5. yes and worked
6. no
7.  yes

below is links-p.cf json parsing working
<img width="1280" alt="Screen Shot 2019-11-12 at 4 11 39 pm" src="https://user-images.githubusercontent.com/44635763/68644032-d74adf00-0567-11ea-94fd-0ee17c86b72f.png">

**Comment by michaeldaltonau** [comment]
@HSAK5G 
Could you please try safari and see what happens?

**Comment by SuperMario22922** [comment]
ok

<img width="1280" alt="Screen Shot 2019-11-12 at 4 21 04 pm" src="https://user-images.githubusercontent.com/44635763/68644246-7bcd2100-0568-11ea-9edd-064bc09a15a6.png">
<img width="1280" alt="Screen Shot 2019-11-12 at 4 20 53 pm" src="https://user-images.githubusercontent.com/44635763/68644248-7bcd2100-0568-11ea-84d7-73d12e6d7ab0.png">

**Comment by michaeldaltonau** [comment]
@HSAK5G Also, is the issue persistent on iPadOS 13 - both Chrome and safari
And who's github pages was it? Could you attach the link please?

Thanks,
**_llui85_**

**Comment by SuperMario22922** [comment]
my ipad is currently out of charge

**Comment by SuperMario22922** [comment]
the github pages was homemadestea58's

**Comment by michaeldaltonau** [comment]
@HSAK5G 
### When you get access to the iPad again:
- Could you go to [chrome://version/](chrome://version/) in Chrome and attach **_all_** the output from the page. This will give me useful information about the exact browser version
- Also, did you have any flags enabled in chrome? Try clicking "Result all to default" and reboot the iPad

Thanks,
**_llui85_**

**Comment by SuperMario22922** [comment]
ok

**Comment by michaeldaltonau** [comment]
@HSAK5G Also, did you encounter this on any other browsers other than chrome?

**Comment by SuperMario22922** [comment]
did not check yet

**Comment by michaeldaltonau** [comment]
@HSAK5G I just tried on Chrome (mobile - V78 on iPadOS 13.2.2), and have encountered no issues with it yet.

**Comment by SuperMario22922** [comment]
on 13.3.2 also

**Comment by michaeldaltonau** [comment]
@HSAK5G I will re-add the JSON functionality for testing, could you please ensure that @Homemadestea58 **does not** revert it.

**Comment by SuperMario22922** [comment]
ok, will tell . tomorrow at **[censored by llui85 - this discussion is public]**

**Comment by SuperMario22922** [comment]
just tested going to github pages but does . not . work

**Comment by michaeldaltonau** [comment]
@Homemadestea58 @HSAK5G 
# Hooray!
![IMG_5809](https://user-images.githubusercontent.com/47158068/68645760-1e879e80-056d-11ea-9b15-134a582677fc.jpeg)

# Cause discovered:
Here is how the JSON system works:
We use AJAX to load `/links.json`.
This success of this download then calls the function `parseLinks` which adds the actual links

## But...
When I test locally, I use a local webserver, which hosts links-portal at the server root (`/`)
links-p.cf hosts the Links Portal at the server root (`/`)

### GitHub Pages, however doesn't host links-portal at the server root (`/`), it hosts them at `/Links-Portal/`, however the hardcoded path is `/links.json`

### To fix this, we just change the path from `/links.json` to `../links.json`, which goes to the directory above portal.html, which is normally the server document root.

**Comment by SuperMario22922** [comment]
good job llui85
