### ISSUE TITLE
JSON not loading

### ISSUE THREAD

**Issue by homemadestea58** [Homemadestea58/Links-Portal#42]
JSON should be loading buttons 
but button not showing up

**Comment by michaeldaltonau** [comment]
What browser is this happening on? If it's a desktop browser please attach JS Console logs
Could you also please attach screenshots/screencasts?

Thanks,
**_llui85_**

# Edit, this is irrelevant, see next comment

**Comment by michaeldaltonau** [comment]
# There is a syntax error in `links.json`, I have fixed it in [#43](https://github.com/Homemadestea58/Links-Portal/pull/43)
