### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by michaeldaltonau** [Homemadestea58/Links-Portal#45]
We should implement a dark mode for the Links-Portal.
We will need to wait until the CSS codebase is cleared up though. (#44)
@Homemadestea58 @HSAK5G What are your thoughts on dark mode overall?

Do you think we should get rid of animations for dark mode?

## Fully covered by dark mode so far
- [x] `<html>` background
- [x] `<body>` border colour
- [x] `<body>` background
- [x] Text colour
- [x] Button background colour
- [x] Button border
- [x] Button text
- [x] Text input text colour
- [x] Text input background colour
- [x] Button hover colours
- [x] Checkbox colours
- [x] Login alert colours

## Information from Discussion
- Keep font the same - Open Sans
- Keep animations, but dial back the colours

## Testing results:
- [x] Safari - macOS
- [x] Chrome - macOS
- [x] Edge Beta - macOS
- [x] Chrome - Windows
- [x] Edge - Windows
- [x] Edge Beta - Windows
- [x] Chrome - iPadOS
- [x] Safari - iPadOS

## Testing comments/note
_Edit this text and put notes or issues that you might discover here_

**Comment by homemadestea58** [comment]
Why do we need dark mode?

**Comment by michaeldaltonau** [comment]
@Homemadestea58 If you view links-portal with dark mode on, the colours and animations can be quite jarring. Besides, it's just a bit of extra CSS, so we might as well add it. It will be auto toggled with the iOS/macOS/Windows dark mode.

**Comment by SuperMario22922** [comment]
yeah. dark mode would be cool! good thinking @llui85. But would dark mode be triggered by iOS/MacOS/Windows dark mode setting or a button on the page?

**Comment by michaeldaltonau** [comment]
@HSAK5G It would be triggered by the OS dark mode, but we might be able to add a manual toggle or something for older computers. We can't work on this though until #44 is cleared up

**Comment by SuperMario22922** [comment]
ok @llui85. are you currently working on #44?

**Comment by michaeldaltonau** [comment]
@HSAK5G Not yet, but I will shortly.

**Comment by SuperMario22922** [comment]
@llui85 And 1 more thing. We should keep the animations for dark mode

**Comment by michaeldaltonau** [comment]
@HSAK5G I'm not sure about animations.

At the moment it goes like this:

**_START REPEAT
  RED
  RED
  GRAY
  ORANGE
  BLUE
  RED
END REPEAT_**

What colours would you recommend for dark mode?

**Comment by SuperMario22922** [comment]
I would suggest using darkish colours like gray, black, etc.
For light mode use light colours like yellow, etc

**Comment by michaeldaltonau** [comment]
@HSAK5G Animations don't really work between gray and black!

**Comment by SuperMario22922** [comment]
Ok, then just use dark colours

**Comment by SuperMario22922** [comment]
That would be my suggestion

**Comment by michaeldaltonau** [comment]
@HSAK5G Maybe we should reduce the colour value (like from `R: 255 G: 0 B: 0`) to `R:100 G: 0 B: 0`

or `R: 184 G: 242 B: 201` to `R: 164 G: 222 B:181`

**Comment by SuperMario22922** [comment]
Ok, good idea. Where are you at merging the .css files

**Comment by michaeldaltonau** [comment]
@HSAK5G Haven't started yet, will probably do it on weekend

What do you think about having 2 style sheets links-light.css and links-dark.css and we use `@media` queries to load the right one?

**Comment by SuperMario22922** [comment]
@llui85 That's a good idea. If you **can't** do that then I guess we can use javascript to attach the css files to the website based on if the OS dark mode is on

**Comment by michaeldaltonau** [comment]
> @llui85 That's a good idea. If you **can't** do that then I guess we can use javascript to attach the css files to the website based on if the OS dark mode is on

We might be able to do that, but then we wouldn't get that nice animation iOS does when toggling dark mode on and off.

Maybe we should just divide the css file into 2 parts (for light and dark mode). Like this

``` CSS
/* Light mode code here */

@media (prefers-color-scheme: dark) {
/* Dark mode code here */
}
```

**Comment by SuperMario22922** [comment]
So to get the animation when switching between dark mode can we do it like:

``` CSS
/* Light mode code here */

@media (prefers-color-scheme: dark) {
/* Dark mode code here */
}
```

Also if this doesn't work then we can use a forever loop in javascript and attach and remove on demand whenever the user turns on or off dark mode!

**Comment by michaeldaltonau** [comment]
> So to get the animation when switching between dark mode can we do it like:
> 
> ``` CSS
> /* Light mode code here */
> 
> @media (prefers-color-scheme: dark) {
> /* Dark mode code here */
> }
> ```
> 
> Also if this doesn't work then we can use a forever loop in javascript and attach and remove on demand whenever the user turns on or off dark mode!

Yes, that will produce the correct animation, and that's probably how we'll do it once I get the codebase issue sorted out

### <ins>**A forever loop in JavaScript is a really bad idea, because JS is synchronous meaning that it can only run 1 thing at a time, not like Scratch. If you had a "forever" loop in JS you would not be able to use anything because the only thing running would be the dark mode checker.**</ins>

**Comment by michaeldaltonau** [comment]
Also, do you still want to keep the animation? (For `<body>` bg colour)

**Comment by SuperMario22922** [comment]
what do you mean by animation

**Comment by michaeldaltonau** [comment]
> what do you mean by animation

I mean how the background colour changes on the portal page

**Comment by SuperMario22922** [comment]
ok. let's keep them but like you said reduce the rgb values

**Comment by michaeldaltonau** [comment]
> ok. let's keep them but like you said reduce the rgb values

Okay, that sounds good. Also, with dark mode, do you want to change the font to something else?

**Comment by SuperMario22922** [comment]
no. otherwise it will look weird. we have to change the font color though!

**Comment by michaeldaltonau** [comment]
> no. otherwise it will look weird. we have to change the font color though!

Really? I think yellow will probably work fine on blue

**Comment by SuperMario22922** [comment]
> > no. otherwise it will look weird. we have to change the font color though!
> 
> Really? I think yellow will probably work fine on blue

Ok, then

**Comment by michaeldaltonau** [comment]
@HSAK5G @Homemadestea58 

The dark mode prototype is live at [links-p.cf](http://links-p.cf).

![IMG_6014](https://user-images.githubusercontent.com/47158068/69920258-b546db80-14d9-11ea-8663-b79995f9cf79.gif)

What do you think about it? You'll need to use a compatible OS such as iPadOS 13, or macOS Mojave.

Any suggestions?

I still need to fix up the login alert colours, but this is difficult because it's hardcoded via bootstrap.

Also @HSAK5G Could you please test this in:
- [x] macOS Mojave or later - Safari
- [x] macOS Mojave or later - Chrome
- [x] macOS Mojave or later - Firefox (if you have it)
- [x] macOS Mojave or later - Edge Beta

If possible, could one of you test this on:
- [x]  Windows 10 - **MUST** be at least "May 2019" update: Google Chrome
- [x]  Windows 10 - **MUST** be at least "May 2019" update: Edge

**Comment by SuperMario22922** [comment]
@llui85 I can test the website on macOS Mojave safari, chrome. I can also download firefox on macOS. I also have windows 10 chrome canary and I can test it on that also if you want.

Also if you want to override bootstrap classes use the ```!important``` class like this:

``` CSS
body {
    color: red !important;
}
```

**Comment by michaeldaltonau** [comment]
> @llui85 I can test the website on macOS Mojave safari, chrome. I also have windows 10 chrome canary and I can test it on that also if you want.

Yes please! Try following [these instructions](https://pureinfotech.com/enable-dark-theme-google-chrome-windows-10/) for Windows (follow the method using Settings!). I haven't opened a PR yet because I need to fix up the login welcome alert colours, when I have the chance

Could you please also test on Edge (using the same instructions to set Windows to dark mode.) You'll need to be on at least "May 2019" update, but ideally be on the latest windows 10 version.

Thanks,
_**llui85**_

P.S To test, just check that everything that is checked off in the checklist up the top works

**Comment by SuperMario22922** [comment]
I also have edge canary and I have dark mode

**Comment by michaeldaltonau** [comment]
> I also have edge canary and I have dark mode

Is this edge beta for macOS?

**Comment by SuperMario22922** [comment]
windows beta

**Comment by michaeldaltonau** [comment]
> windows beta

Could you also please try with [Edge Beta for Mac](https://www.microsoftedgeinsider.com/en-au/)

**Comment by SuperMario22922** [comment]
ok

**Comment by SuperMario22922** [comment]
can you please edit the checklist

**Comment by michaeldaltonau** [comment]
> can you please edit the checklist

done!

**Comment by SuperMario22922** [comment]
Thanks

**Comment by SuperMario22922** [comment]
all done @llui85

**Comment by SuperMario22922** [comment]
all platforms and browser combinations tested 👍

**Comment by HSAK5G** [comment]
maybe you should ipad os and also iphone os to the list to test. I can also test these devices.

**Comment by michaeldaltonau** [comment]
> all platforms and browser combinations tested 👍

> maybe you should ipad os and also iphone os to the list to test. I can also test these devices.

Good work! Did you notice anything that didn't work or looked weird on any of the browsers?

Also iPadOS Safari and iOS Safari are essentially the same browser, so we don't need to do anymore testing

Thanks,
**_llui85_**

**Comment by SuperMario22922** [comment]
No, nothing wierd

**Comment by michaeldaltonau** [comment]
@HSAK5G @Homemadestea58 

Do you have any suggestions on how I could improve the dark mode? (Different colours etc)

**Comment by SuperMario22922** [comment]
@llui85 No, it is already good. One thing is you can start the animations in the background with darker colours.

**Comment by michaeldaltonau** [comment]
> @llui85 No, it is already good. One thing is you can start the animations in the background with darker colours.

I'm just not sure what colours to use on it, because most of the colours are too light, and have bad contrast with the text.

**Comment by SuperMario22922** [comment]
@llui85 Ok, then it is fine!

**Comment by michaeldaltonau** [comment]
> @llui85 Ok, then it is fine!

Okay! Does @Homemadestea58 have any comments?

**Comment by homemadestea58** [comment]
@llui85 With the dark mode is there any way to toggle it manually?

**Comment by michaeldaltonau** [comment]
> @llui85 With the dark mode is there any way to toggle it manually?

No, there isn't currently. Do you want me to work on an option in the customise page to manually toggle it or force it on and off? (with cookies)

**Comment by homemadestea58** [comment]
If it is possible or else I will just merge the branches and we can have it live on the official Links-Portal

**Comment by SuperMario22922** [comment]
🚀

**Comment by michaeldaltonau** [comment]
> If it is possible or else I will just merge the branches and we can have it live on the official Links-Portal

Don't merge this yet, because I still need to fix up login alert colours, but once I've done that, I'll open a PR for you to merge in.

Thanks,
_**llui85**_

**Comment by homemadestea58** [comment]
Ok
I am going to change some settings so that only PRs can be merged me

**Comment by michaeldaltonau** [comment]
> Ok
> I am going to change some settings so that only PRs can be merged me

Why? Only me and HSAK5G can merge them anyway.

**Comment by SuperMario22922** [comment]
Good job on what you did so far @llui85. Keep up the good work!

**Comment by homemadestea58** [comment]
Ok
I will leave them but tell me before you merge them

**Comment by SuperMario22922** [comment]
Ok, i will @Homemadestea58

**Comment by michaeldaltonau** [comment]
@Homemadestea58 

What do you think of the Links-Portal theme idea?

**Comment by SuperMario22922** [comment]
I love it ❤️  @llui85 .

**Comment by homemadestea58** [comment]
Yes, I like it
See what you can do once you have finished dark mode.

**Comment by michaeldaltonau** [comment]
> Yes, I like it
> See what you can do once you have finished dark mode.

Okay, I'll open another issue about themes once I get dark mode sorted out.

**Comment by homemadestea58** [comment]
Ok

**Comment by SuperMario22922** [comment]
@llui85 When you get the login alert sorted out please tell me so I can test it. 🚀

**Comment by homemadestea58** [comment]
Are the login alerts done yet?

**Comment by michaeldaltonau** [comment]
> Are the login alerts done yet?

Yep, they're ready for merging now. I'll open a PR in a few hours
