### ISSUE TITLE
Syntax Error in google Slides code

### ISSUE THREAD

**Issue by michaeldaltonau** [Homemadestea58/Links-Portal#7]
Smart quotes ‘ and ’ are used instead of regular quotes ' and '
This causes a JavaScript syntax error.
Most web browsers block also block window.open so we should use location to avoid browsers classifying them as popups

`<input class=button type="button" value="Google Slides" onclick="window.open(‘https://slides.google.com’)" />` - <b>Causes an error</b>

**Comment by homemadestea58** [comment]
Can’t most people want the website to open in a new tab

**Comment by michaeldaltonau** [comment]
This is fixed
